import type { OxlintConfig } from 'oxlint';

export const ignorePatterns = [
	'tests/*/fixtures/**/fail{.*,/**}',
	'tests/node/fixtures/package-commonjs/pass.js',
	'tests/cli/fixtures/js-config-commonjs/',
	'tests/typescript/fixtures/allow-ts-extensions/',
	'**/package-lock.json',
	'**/pnpm-lock.yaml',
	'{tmp,temp,.tmp,.temp,__tmp__,__temp__}/**',
	'**/*.min.js',
	'**/dist/**',
	'**/node_modules/**',
	'**/vendor/**',
	'**/.cache/**',
	'**/.vitepress',
	'**/CLAUDE.md',
	'**/CLAUDE.local.md',
	'**/.claude',
	'**/AI.md',
	'**/AGENT.md',
	'**/PROMPT.md',
	'**/PROMPTING.md',
	'**/.cursorrules',
	'**/.cursorignore',
	'**/.cursormem.json',
	'**/.cursorhistory',
	'**/copilot.json',
	'**/copilot.config.json',
	'**/copilot.md',
	'**/skills/**/*.md/**',
] satisfies NonNullable<OxlintConfig['ignorePatterns']>;
