import type { OxlintConfig } from 'oxlint';

export const overrides = [
	{
		files: [
			'**/*.sw.{js,ts}',
		],
		rules: {
			'no-restricted-globals': [
				'error',
				'addEventListener',
				'blur',
				'close',
				'closed',
				'confirm',
				'defaultStatus',
				'defaultstatus',
				'event',
				'external',
				'find',
				'focus',
				'frameElement',
				'frames',
				'history',
				'innerHeight',
				'innerWidth',
				'length',
				'location',
				'locationbar',
				'menubar',
				'moveBy',
				'moveTo',
				'name',
				'onblur',
				'onerror',
				'onfocus',
				'onload',
				'onresize',
				'onunload',
				'open',
				'opener',
				'opera',
				'outerHeight',
				'outerWidth',
				'pageXOffset',
				'pageYOffset',
				'parent',
				'print',
				'removeEventListener',
				'resizeBy',
				'resizeTo',
				'screen',
				'screenLeft',
				'screenTop',
				'screenX',
				'screenY',
				'scroll',
				'scrollbars',
				'scrollBy',
				'scrollTo',
				'scrollX',
				'scrollY',
				'status',
				'statusbar',
				'stop',
				'toolbar',
				'top',
			],
		},
	},
	{
		files: [
			'**/src/**/*',
		],
		rules: {
			'import/no-dynamic-require': 'error',
		},
	},
	{
		files: [
			'**/*.{js,jsx,cjs,mjs}',
			'**/*.{ts,tsx,mts,cts}',
			'**/*.vue',
		],
		rules: {
			'no-nested-ternary': 'off',
			'unicorn/catch-error-name': 'error',
			'unicorn/consistent-assert': 'error',
			'unicorn/consistent-date-clone': 'error',
			'unicorn/consistent-empty-array-spread': 'error',
			'unicorn/consistent-existence-index-check': 'error',
			'unicorn/consistent-function-scoping': 'off',
			'unicorn/custom-error-definition': 'off',
			'unicorn/empty-brace-spaces': 'error',
			'unicorn/error-message': 'error',
			'unicorn/escape-case': 'error',
			'unicorn/explicit-length-check': 'off',
			'unicorn/filename-case': 'error',
			'unicorn/import-style': 'error',
			'unicorn/new-for-builtins': 'error',
			'unicorn/no-abusive-eslint-disable': 'off',
			'unicorn/no-accessor-recursion': 'error',
			'unicorn/no-anonymous-default-export': 'off',
			'unicorn/no-array-callback-reference': 'error',
			'unicorn/no-array-for-each': 'off',
			'unicorn/no-array-method-this-argument': 'error',
			'unicorn/no-array-reduce': 'error',
			'unicorn/no-array-reverse': 'warn',
			'unicorn/no-array-sort': 'off',
			'unicorn/no-await-expression-member': 'error',
			'unicorn/no-await-in-promise-methods': 'error',
			'unicorn/no-console-spaces': 'error',
			'unicorn/no-document-cookie': 'error',
			'unicorn/no-empty-file': 'error',
			'unicorn/no-hex-escape': 'error',
			'unicorn/no-immediate-mutation': 'error',
			'unicorn/no-instanceof-builtins': 'error',
			'unicorn/no-invalid-fetch-options': 'error',
			'unicorn/no-invalid-remove-event-listener': 'error',
			'unicorn/no-lonely-if': 'error',
			'unicorn/no-magic-array-flat-depth': 'error',
			'unicorn/no-negated-condition': 'error',
			'unicorn/no-negation-in-equality-check': 'error',
			'unicorn/no-nested-ternary': 'error',
			'unicorn/no-new-array': 'error',
			'unicorn/no-new-buffer': 'off',
			'unicorn/no-null': 'off',
			'unicorn/no-object-as-default-parameter': 'error',
			'unicorn/no-process-exit': 'off',
			'unicorn/no-single-promise-in-promise-methods': 'error',
			'unicorn/no-static-only-class': 'error',
			'unicorn/no-thenable': 'error',
			'unicorn/no-this-assignment': 'error',
			'unicorn/no-typeof-undefined': 'error',
			'unicorn/no-unnecessary-array-flat-depth': 'error',
			'unicorn/no-unnecessary-array-splice-count': 'error',
			'unicorn/no-unnecessary-await': 'error',
			'unicorn/no-unnecessary-slice-end': 'error',
			'unicorn/no-unreadable-array-destructuring': 'error',
			'unicorn/no-unreadable-iife': 'error',
			'unicorn/no-useless-collection-argument': 'error',
			'unicorn/no-useless-error-capture-stack-trace': 'error',
			'unicorn/no-useless-fallback-in-spread': 'error',
			'unicorn/no-useless-length-check': 'error',
			'unicorn/no-useless-promise-resolve-reject': 'error',
			'unicorn/no-useless-spread': 'error',
			'unicorn/no-useless-switch-case': 'error',
			'unicorn/no-useless-undefined': 'error',
			'unicorn/no-zero-fractions': 'error',
			'unicorn/number-literal-case': 'error',
			'unicorn/numeric-separators-style': 'error',
			'unicorn/prefer-add-event-listener': 'error',
			'unicorn/prefer-array-find': 'error',
			'unicorn/prefer-array-flat': 'error',
			'unicorn/prefer-array-flat-map': 'error',
			'unicorn/prefer-array-index-of': 'error',
			'unicorn/prefer-array-some': 'error',
			'unicorn/prefer-at': 'error',
			'unicorn/prefer-bigint-literals': 'error',
			'unicorn/prefer-blob-reading-methods': 'error',
			'unicorn/prefer-class-fields': 'error',
			'unicorn/prefer-classlist-toggle': 'error',
			'unicorn/prefer-code-point': 'error',
			'unicorn/prefer-date-now': 'error',
			'unicorn/prefer-default-parameters': 'error',
			'unicorn/prefer-dom-node-append': 'error',
			'unicorn/prefer-dom-node-dataset': 'error',
			'unicorn/prefer-dom-node-remove': 'error',
			'unicorn/prefer-dom-node-text-content': 'error',
			'unicorn/prefer-event-target': 'error',
			'unicorn/prefer-export-from': 'off',
			'unicorn/prefer-global-this': 'error',
			'unicorn/prefer-import-meta-properties': 'off',
			'unicorn/prefer-includes': 'error',
			'unicorn/prefer-keyboard-event-key': 'error',
			'unicorn/prefer-logical-operator-over-ternary': 'error',
			'unicorn/prefer-math-min-max': 'error',
			'unicorn/prefer-math-trunc': 'error',
			'unicorn/prefer-modern-dom-apis': 'error',
			'unicorn/prefer-modern-math-apis': 'error',
			'unicorn/prefer-module': 'off',
			'unicorn/prefer-native-coercion-functions': 'error',
			'unicorn/prefer-negative-index': 'error',
			'unicorn/prefer-node-protocol': 'off',
			'unicorn/prefer-number-properties': 'error',
			'unicorn/prefer-object-from-entries': 'error',
			'unicorn/prefer-optional-catch-binding': 'error',
			'unicorn/prefer-prototype-methods': 'error',
			'unicorn/prefer-query-selector': 'error',
			'unicorn/prefer-reflect-apply': 'error',
			'unicorn/prefer-regexp-test': 'error',
			'unicorn/prefer-response-static-json': 'error',
			'unicorn/prefer-set-has': 'error',
			'unicorn/prefer-set-size': 'error',
			'unicorn/prefer-single-call': 'error',
			'unicorn/prefer-spread': 'off',
			'unicorn/prefer-string-raw': 'error',
			'unicorn/prefer-string-replace-all': 'error',
			'unicorn/prefer-string-slice': 'error',
			'unicorn/prefer-string-starts-ends-with': 'error',
			'unicorn/prefer-string-trim-start-end': 'error',
			'unicorn/prefer-structured-clone': 'error',
			'unicorn/prefer-ternary': 'off',
			'unicorn/prefer-top-level-await': 'off',
			'unicorn/prefer-type-error': 'error',
			'unicorn/relative-url-style': 'error',
			'unicorn/require-array-join-separator': 'error',
			'unicorn/require-module-attributes': 'error',
			'unicorn/require-module-specifiers': 'error',
			'unicorn/require-number-to-fixed-digits-argument': 'error',
			'unicorn/require-post-message-target-origin': 'off',
			'unicorn/switch-case-braces': 'error',
			'unicorn/text-encoding-identifier-case': 'error',
			'unicorn/throw-new-error': 'error',
		},
		plugins: [
			'unicorn',
		],
	},
	{
		files: [
			'**/*.{ts,tsx,mts,cts}',
		],
		rules: {
			'constructor-super': 'off',
			'getter-return': 'off',
			'no-class-assign': 'off',
			'no-const-assign': 'off',
			'no-dupe-class-members': 'off',
			'no-dupe-keys': 'off',
			'no-func-assign': 'off',
			'no-import-assign': 'off',
			'no-new-native-nonconstructor': 'off',
			'no-obj-calls': 'off',
			'no-redeclare': 'off',
			'no-setter-return': 'off',
			'no-this-before-super': 'off',
			'no-unreachable': 'off',
			'no-unsafe-negation': 'off',
			'no-with': 'off',
			'prefer-const': [
				'error',
				{
					destructuring: 'any',
					ignoreReadBeforeAssign: true,
				},
			],
			'no-unused-expressions': 'error',
			'no-unused-vars': [
				'error',
				{
					args: 'after-used',
					ignoreRestSiblings: true,
					vars: 'all',
					argsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
				},
			],
			'no-empty-function': [
				'error',
				{
					allow: [
						'arrowFunctions',
						'functions',
						'methods',
					],
				},
			],
			'func-style': 'off',
			'no-shadow': [
				'error',
				{
					allow: [
						'test',
						'describe',
						'runTestSuite',
						'onFinish',
						'fixture',
					],
				},
			],
			'unicorn/no-array-callback-reference': 'off',
			'unicorn/no-useless-undefined': 'off',
			'import/extensions': 'off',
			'typescript/ban-ts-comment': 'error',
			'typescript/no-duplicate-enum-values': 'error',
			'typescript/no-empty-object-type': 'error',
			'typescript/no-explicit-any': [
				'error',
				{
					fixToUnknown: false,
					ignoreRestArgs: true,
				},
			],
			'typescript/no-extra-non-null-assertion': 'error',
			'typescript/no-misused-new': 'error',
			'typescript/no-namespace': 'error',
			'typescript/no-non-null-asserted-optional-chain': 'error',
			'typescript/no-require-imports': 'error',
			'typescript/no-this-alias': 'error',
			'typescript/no-unnecessary-type-constraint': 'error',
			'typescript/no-unsafe-declaration-merging': 'error',
			'typescript/no-unsafe-function-type': 'error',
			'typescript/no-wrapper-object-types': 'error',
			'typescript/prefer-as-const': 'error',
			'typescript/prefer-namespace-keyword': 'error',
			'typescript/triple-slash-reference': 'error',
			'typescript/consistent-type-definitions': [
				'error',
				'type',
			],
			'typescript/consistent-type-imports': [
				'error',
				{
					fixStyle: 'inline-type-imports',
				},
			],
			'typescript/no-import-type-side-effects': 'error',
		},
		plugins: [
			'typescript',
			'unicorn',
		],
	},
	{
		files: [
			'**/*.{js,jsx,cjs,mjs}',
			'**/*.{ts,tsx,mts,cts}',
			'**/*.vue',
		],
		rules: {
			'prefer-regex-literals': [
				'error',
				{
					disallowRedundantWrapping: true,
				},
			],
			'no-invalid-regexp': 'off',
			'no-useless-backreference': 'off',
			'no-empty-character-class': 'off',
			'promise/always-return': 'off',
			'promise/no-return-wrap': 'error',
			'promise/param-names': 'error',
			'promise/catch-or-return': [
				'error',
				{
					allowThen: true,
				},
			],
			'promise/no-nesting': 'warn',
			'promise/no-promise-in-callback': 'warn',
			'promise/no-callback-in-promise': 'warn',
			'promise/avoid-new': 'off',
			'promise/no-new-statics': 'error',
			'promise/valid-params': 'warn',
		},
		plugins: [
			'promise',
		],
	},
	{
		files: [
			'**/*.cjs',
			'**/*.cts',
		],
		rules: {
			'node/no-exports-assign': 'error',
		},
		plugins: [
			'node',
		],
	},
	{
		files: [
			'**/scripts/**/*.{js,ts}',
		],
		rules: {
			'no-console': 'off',
			'node/no-exports-assign': 'error',
		},
		plugins: [
			'node',
		],
	},
	{
		files: [
			'**/*.js',
			'**/*.ts',
			'**/*.mjs',
			'**/*.mts',
		],
		rules: {
			'node/no-exports-assign': 'error',
		},
		plugins: [
			'node',
		],
	},
	{
		files: [
			'**/*.{js,ts,mjs,cjs,mts,cts}',
		],
		rules: {
			'node/global-require': 'error',
			'node/no-mixed-requires': [
				'error',
				{
					allowCall: true,
					grouping: true,
				},
			],
			'node/no-new-require': 'error',
			'node/no-path-concat': 'error',
		},
		plugins: [
			'node',
		],
	},
	{
		files: [
			'**/*.{ts,tsx,mts,cts}',
		],
		rules: {
			'node/global-require': 'off',
		},
		plugins: [
			'node',
		],
	},
	{
		files: [
			'**/cli.{js,ts}',
			'**/cli/**/*.{js,ts}',
		],
		rules: {
			'node/no-exports-assign': 'error',
		},
		plugins: [
			'node',
		],
	},
	{
		files: [
			'**/*.vue',
		],
		rules: {
			'unicorn/filename-case': [
				'error',
				{
					case: 'pascalCase',
				},
			],
		},
		plugins: [
			'unicorn',
		],
	},
	{
		files: [
			'**/*.{jsx,tsx}',
		],
		rules: {
			'react/display-name': 'error',
			'react/jsx-key': 'error',
			'react/jsx-no-comment-textnodes': 'error',
			'react/jsx-no-duplicate-props': 'error',
			'react/jsx-no-target-blank': 'error',
			'react/jsx-no-undef': 'error',
			'react/no-children-prop': 'error',
			'react/no-danger-with-children': 'error',
			'react/no-direct-mutation-state': 'error',
			'react/no-find-dom-node': 'error',
			'react/no-is-mounted': 'error',
			'react/no-render-return-value': 'error',
			'react/no-string-refs': 'error',
			'react/no-unescaped-entities': 'error',
			'react/no-unknown-property': 'error',
			'react/no-unsafe': 'off',
			'react/react-in-jsx-scope': 'off',
			'unicorn/filename-case': [
				'error',
				{
					case: 'pascalCase',
					ignore: [
						String.raw`\.spec\.tsx$`,
					],
				},
			],
			'react/rules-of-hooks': 'error',
			'react/exhaustive-deps': 'warn',
		},
		plugins: [
			'react',
			'unicorn',
		],
	},
] satisfies NonNullable<OxlintConfig['overrides']>;
