import type { OxlintConfig } from 'oxlint';

/** Additional ESLint core rules. */
export const eslintRules = {
	'accessor-pairs': 'error',
	'array-callback-return': [
		'error',
		{
			allowImplicit: true,
		},
	],
	'arrow-body-style': [
		'error',
		'as-needed',
	],
	'block-scoped-var': 'error',
	complexity: [
		'warn',
		10,
	],
	curly: 'error',
	'default-case': [
		'error',
		{
			commentPattern: '^no default$',
		},
	],
	'default-case-last': 'error',
	'default-param-last': 'error',
	eqeqeq: [
		'error',
		'always',
		{
			null: 'ignore',
		},
	],
	'func-names': 'warn',
	'func-style': [
		'error',
		'declaration',
		{
			allowArrowFunctions: true,
		},
	],
	'grouped-accessor-pairs': [
		'error',
		'getBeforeSet',
	],
	'guard-for-in': 'error',
	'max-nested-callbacks': [
		'warn',
		6,
	],
	'max-params': [
		'warn',
		5,
	],
	'no-alert': 'warn',
	'no-array-constructor': 'error',
	'no-bitwise': 'error',
	'no-caller': 'error',
	'no-console': 'warn',
	'no-constructor-return': 'error',
	'no-else-return': [
		'error',
		{
			allowElseIf: false,
		},
	],
	'no-empty-function': [
		'error',
		{
			allow: [
				'arrowFunctions',
				'functions',
				'methods',
			],
		},
	],
	'no-eq-null': 'error',
	'no-eval': 'error',
	'no-extend-native': 'error',
	'no-extra-bind': 'error',
	'no-extra-label': 'error',
	'no-implicit-globals': 'error',
	'no-implied-eval': 'error',
	'no-iterator': 'error',
	'no-label-var': 'error',
	'no-labels': [
		'error',
		{
			allowLoop: true,
			allowSwitch: false,
		},
	],
	'no-lone-blocks': 'error',
	'no-lonely-if': 'error',
	'no-loop-func': 'error',
	'no-multi-assign': [
		'error',
	],
	'no-multi-str': 'error',
	'no-nested-ternary': 'error',
	'no-new': 'error',
	'no-new-func': 'error',
	'no-object-constructor': 'error',
	'no-new-wrappers': 'error',
	'no-plusplus': 'error',
	'no-promise-executor-return': 'error',
	'no-proto': 'error',
	'no-restricted-globals': [
		'error',
		'addEventListener',
		'blur',
		'close',
		'closed',
		'confirm',
		'defaultStatus',
		'defaultstatus',
		'event',
		'external',
		'find',
		'focus',
		'frameElement',
		'frames',
		'history',
		'innerHeight',
		'innerWidth',
		'length',
		'location',
		'locationbar',
		'menubar',
		'moveBy',
		'moveTo',
		'name',
		'onblur',
		'onerror',
		'onfocus',
		'onload',
		'onresize',
		'onunload',
		'open',
		'opener',
		'opera',
		'outerHeight',
		'outerWidth',
		'pageXOffset',
		'pageYOffset',
		'parent',
		'print',
		'removeEventListener',
		'resizeBy',
		'resizeTo',
		'screen',
		'screenLeft',
		'screenTop',
		'screenX',
		'screenY',
		'scroll',
		'scrollbars',
		'scrollBy',
		'scrollTo',
		'scrollX',
		'scrollY',
		'self',
		'status',
		'statusbar',
		'stop',
		'toolbar',
		'top',
	],
	'no-restricted-properties': [
		'error',
		{
			message: 'arguments.callee is deprecated',
			object: 'arguments',
			property: 'callee',
		},
		{
			message: 'Please use Number.isFinite instead',
			object: 'global',
			property: 'isFinite',
		},
		{
			message: 'Please use Number.isFinite instead',
			object: 'self',
			property: 'isFinite',
		},
		{
			message: 'Please use Number.isFinite instead',
			object: 'window',
			property: 'isFinite',
		},
		{
			message: 'Please use Number.isNaN instead',
			object: 'global',
			property: 'isNaN',
		},
		{
			message: 'Please use Number.isNaN instead',
			object: 'self',
			property: 'isNaN',
		},
		{
			message: 'Please use Number.isNaN instead',
			object: 'window',
			property: 'isNaN',
		},
		{
			message: 'Please use Object.defineProperty instead.',
			property: '__defineGetter__',
		},
		{
			message: 'Please use Object.defineProperty instead.',
			property: '__defineSetter__',
		},
		{
			message: 'Use the exponentiation operator (**) instead.',
			object: 'Math',
			property: 'pow',
		},
	],
	'no-return-assign': [
		'error',
		'always',
	],
	'no-script-url': 'error',
	'no-self-compare': 'error',
	'no-sequences': 'error',
	'no-shadow': [
		'error',
		{
			allow: [
				'test',
				'describe',
				'runTestSuite',
				'onFinish',
				'fixture',
			],
		},
	],
	'no-throw-literal': 'error',
	'no-unneeded-ternary': [
		'error',
		{
			defaultAssignment: false,
		},
	],
	'no-unused-expressions': [
		'error',
		{
			allowShortCircuit: false,
			allowTaggedTemplates: false,
			allowTernary: false,
		},
	],
	'no-useless-computed-key': 'error',
	'no-useless-concat': 'error',
	'no-useless-constructor': 'error',
	'no-useless-rename': [
		'error',
		{
			ignoreDestructuring: false,
			ignoreExport: false,
			ignoreImport: false,
		},
	],
	'no-useless-return': 'error',
	'no-var': 'error',
	'no-void': 'error',
	'object-shorthand': [
		'error',
		'always',
		{
			ignoreConstructors: false,
		},
	],
	'operator-assignment': [
		'error',
		'always',
	],
	'prefer-arrow-callback': [
		'error',
		{
			allowNamedFunctions: false,
			allowUnboundThis: true,
		},
	],
	'prefer-const': [
		'error',
		{
			destructuring: 'any',
			ignoreReadBeforeAssign: true,
		},
	],
	'prefer-destructuring': [
		'error',
		{
			VariableDeclarator: {
				array: false,
				object: true,
			},
			AssignmentExpression: {
				array: false,
				object: false,
			},
		},
		{
			enforceForRenamedProperties: false,
		},
	],
	'prefer-exponentiation-operator': 'error',
	'prefer-numeric-literals': 'error',
	'prefer-object-spread': 'error',
	'prefer-promise-reject-errors': [
		'error',
		{
			allowEmptyReject: true,
		},
	],
	'prefer-regex-literals': [
		'error',
		{
			disallowRedundantWrapping: true,
		},
	],
	'prefer-spread': 'error',
	'prefer-template': 'error',
	radix: 'error',
	'symbol-description': 'error',
	'unicode-bom': [
		'error',
		'never',
	],
	'vars-on-top': 'error',
	yoda: 'error',
} satisfies NonNullable<OxlintConfig['rules']>;
