import type { DummyRuleMap } from 'oxlint';

/**
 * Confusing browser globals that should not be used without explicit window. prefix.
 * From the confusing-browser-globals package.
 */
const confusingBrowserGlobals = [
	'addEventListener',
	'blur',
	'close',
	'closed',
	'confirm',
	'defaultStatus',
	'defaultstatus',
	'event',
	'external',
	'find',
	'focus',
	'frameElement',
	'frames',
	'history',
	'innerHeight',
	'innerWidth',
	'isFinite',
	'isNaN',
	'length',
	'location',
	'locationbar',
	'menubar',
	'moveBy',
	'moveTo',
	'name',
	'onblur',
	'onerror',
	'onfocus',
	'onload',
	'onresize',
	'onunload',
	'open',
	'opener',
	'opera',
	'origin',
	'outerHeight',
	'outerWidth',
	'pageXOffset',
	'pageYOffset',
	'parent',
	'print',
	'removeEventListener',
	'resizeBy',
	'resizeTo',
	'screen',
	'screenLeft',
	'screenTop',
	'screenX',
	'screenY',
	'scroll',
	'scrollbars',
	'scrollBy',
	'scrollTo',
	'scrollX',
	'scrollY',
	'self',
	'status',
	'statusbar',
	'stop',
	'toolbar',
	'top',
];

/**
 * Callback names from manten and tasuku that are commonly shadowed
 * in test/task scopes. Allowed in no-shadow.
 */
export const shadowAllowList = [
	'test',
	'describe',
	'runTestSuite',
	'onFinish',
	'fixture',
	'task',
	'setTitle',
	'setError',
	'setWarning',
	'setStatus',
	'setOutput',
];

/**
 * ESLint core rules — matches src/configs/eslint.ts
 */
export const eslintRules: DummyRuleMap = {
	'accessor-pairs': 'error',
	'array-callback-return': ['error', { allowImplicit: true }],
	'arrow-body-style': ['error', 'as-needed'],
	'block-scoped-var': 'error',
	curly: 'error',
	'default-case': 'error',
	'default-case-last': 'error',
	'default-param-last': 'error',
	'dot-notation': ['error', { allowKeywords: true }],
	eqeqeq: ['error', 'always', { null: 'ignore' }],
	'func-names': 'warn',
	'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
	'getter-return': ['error', { allowImplicit: true }],
	'grouped-accessor-pairs': ['error', 'getBeforeSet'],
	'guard-for-in': 'error',
	'no-array-constructor': 'error',
	'no-bitwise': 'error',
	'no-caller': 'error',
	'no-cond-assign': ['error', 'always'],
	'no-constructor-return': 'error',
	'no-else-return': ['error', { allowElseIf: false }],
	'no-empty': ['error', { allowEmptyCatch: true }],
	'no-empty-function': ['error', {
		allow: ['arrowFunctions', 'functions', 'methods'],
	}],
	'no-eq-null': 'error',
	'no-eval': 'error',
	'no-extend-native': 'error',
	'no-extra-bind': 'error',
	'no-extra-label': 'error',
	'no-implied-eval': 'error',
	'no-iterator': 'error',
	'no-label-var': 'error',
	'no-labels': ['error', {
		allowLoop: true,
		allowSwitch: false,
	}],
	'no-lone-blocks': 'error',
	'no-lonely-if': 'error',
	'no-loop-func': 'error',
	'no-multi-assign': 'error',
	'no-multi-str': 'error',
	'no-nested-ternary': 'error',
	'no-new': 'error',
	'no-new-func': 'error',
	'no-object-constructor': 'error',
	'no-new-wrappers': 'error',
	'no-plusplus': 'error',
	'no-promise-executor-return': 'error',
	'no-proto': 'error',
	'no-return-assign': ['error', 'always'],
	'no-script-url': 'error',
	'no-self-assign': ['error', { props: true }],
	'no-self-compare': 'error',
	'no-sequences': 'error',
	'no-shadow': ['error', { allow: shadowAllowList }],
	'no-throw-literal': 'error',
	'no-unneeded-ternary': ['error', { defaultAssignment: false }],
	'no-unused-expressions': ['error', {
		allowShortCircuit: false,
		allowTaggedTemplates: false,
		allowTernary: false,
	}],
	'no-unused-vars': ['error', {
		args: 'after-used',
		ignoreRestSiblings: true,
		vars: 'all',
	}],
	'no-useless-call': 'off',
	'no-useless-computed-key': 'error',
	'no-useless-concat': 'error',
	'no-useless-constructor': 'error',
	'no-useless-rename': 'error',
	'no-useless-return': 'error',
	'no-var': 'error',
	'no-void': 'error',
	'operator-assignment': ['error', 'always'],
	'prefer-const': ['error', {
		destructuring: 'any',
		ignoreReadBeforeAssign: true,
	}],
	'prefer-destructuring': ['error', {
		VariableDeclarator: {
			array: false,
			object: true,
		},
		AssignmentExpression: {
			array: false,
			object: false,
		},
	}],
	'prefer-exponentiation-operator': 'error',
	'prefer-numeric-literals': 'error',
	'prefer-object-spread': 'error',
	'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
	'prefer-rest-params': 'off',
	'prefer-spread': 'error',
	'prefer-template': 'error',
	radix: 'error',
	'symbol-description': 'error',
	'unicode-bom': ['error', 'never'],
	'valid-typeof': ['error', { requireStringLiterals: true }],
	'vars-on-top': 'error',
	yoda: 'error',

	// Warnings
	complexity: ['warn', 10],
	'max-nested-callbacks': ['warn', 6],
	'max-params': ['warn', 5],
	'no-alert': 'warn',
	'no-console': 'warn',
	'no-constant-condition': 'warn',
	'no-restricted-globals': ['error', ...confusingBrowserGlobals],

	// Disabled
	'no-duplicate-imports': 'off',
	'no-use-before-define': 'off',
	'no-warning-comments': 'off',
	'require-await': 'off',
};
