name: Test
on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Use Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          cache: true

      - name: Type check
        run: pnpm type-check

      - name: Test
        run: |
          pnpm build
          pnpm test

      - name: Lint
        run: pnpm lint

      - name: Test Node.js 20.20.0
        if: matrix.os == 'ubuntu-latest'
        run: pnx node@20.20.0 --import tsx tests/index.ts
