name: Test
on:
  push:
    branches: [develop]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6

      - name: Get pnpm store directory
        shell: bash
        run: echo "PNPM_STORE=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        name: Cache pnpm
        with:
          path: ${{ env.PNPM_STORE }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Type check
        run: pnpm type-check

      - name: Test
        run: |
          pnpm build
          pnpm test

      - name: Lint
        run: pnpm lint
